genomes:
  test_genome_without_rnaseq:
    augustus_dataset_name: "cacao"
    busco_lineage: "embryophyta_odb10"
    fasta_file: "test-data/genome.fa.gz"
    helixer_lineage: "land_plant"
    label: "Arabidopsis fragment"
    ncbi_family: "Brassicales"
    softmasked: True
    taxon_id: 3702
    tiberius_model: "Eudicotyledons"
  test_genome_with_rnaseq:
    augustus_dataset_name: "cacao"
    busco_lineage: "embryophyta_odb10"
    fasta_file: "test-data/genome.fa.gz"
    helixer_lineage: "land_plant"
    label: "Arabidopsis fragment with RNAseq"
    ncbi_family: "Brassicales"
    rnaseq: "test-data/RNAseq.bam"
    softmasked: True
    taxon_id: 3702
    tiberius_model: "Eudicotyledons"
    overrides:
      funannotate:
        busco_lineage: "viridiplantae_odb10"
parameters:
  busco_min_training_models: 7
