tools:
  braker3:
    container: "docker://teambraker/braker3:v3.0.7.1"
    result_files:
      - "braker.gff3"
      - "braker.gtf"
  helixer:
    container: "docker://gglyptodon/helixer-docker:helixer_v0.3.6_cuda_12.2.2-cudnn8"
    result_files:
      - "helixer.gff3"
    lineages:
      - "fungi"
      - "invertebrate"
      - "land_plant"
      - "vertebrate"
  tiberius:
    container: "docker://larsgabriel23/tiberius@sha256:9d24469611264ca55b5ef14a4708e632f0f6f7c11c97304ccf9cc4993d3560dd"
    result_files:
      - "tiberius.gtf"
    models:
      Eudicotyledons: "https://bioinf.uni-greifswald.de/bioinf/tiberius/models/eudicotyledons_weights.tar.gz"
      Sordariomycota: "https://bioinf.uni-greifswald.de/bioinf/tiberius/models/sordariomycota_weights.tar.gz" # rhynco
  funannotate:
    container: "docker://ghcr.io/tomharrop/container-funannotate:1.8.17_cv5"
    result_files:
      - "funannotate.gff3"
utils:
  bbmap: "docker://quay.io/biocontainers/bbmap:39.01--h92535d8_1"
  debian: "docker://debian:stable-20250113"
  samtools: "docker://quay.io/biocontainers/samtools:1.23--h96c455f_0"
  wget: "docker://quay.io/biocontainers/gnu-wget:1.18--hb829ee6_10"

qc:
  annooddities:
    container: "docker://gemygk/annooddities:v0.1.0"
    result_files:
      - "AnnoOddities.tar.gz"
      - "AnnoOddities.gff"
      - "AnnoOddities.combined_statistics.json"
      - "AnnoOddities.oddity_summary.txt"
  atol_qc_annotation:
    container: "docker://quay.io/biocontainers/atol-qc-annotation:0.1.4--pyhdfd78af_0"
    result_files:
      - "omark_summary.json"
      - "proteins.faa"
      - "short_summary.specific.busco.json"
      - "short_summary.specific.busco.txt"
